### ISSUE TITLE
Recomended Camera

### ISSUE THREAD

**Issue by kevilay** [alleexx/cam-putting-py#13]
Great work on this project. I see you have a list of cameras and at the top you can't guarentee functionality. Do you have a recomended camera that you know works well yourself? The PS4 seems to be the best framerate and is pretty cheap.

**Comment by alleexx** [comment]
Just ask in the discord if you have not done so already. Lots are working it seems. A lot of people use the streamcam or the kiyo pro. PS4 needs custom firmware, so only if you are really into tech.
