### ISSUE TITLE
OpenAPI Advanced Club Data Viewer "Hangs" for Next Tee Shot After Finishing Hole

### ISSUE THREAD

**Issue by maconmatt** [alleexx/cam-putting-py#14]
I’ve run into an issue that I wonder if others have experienced. I’m currently using my R10 with the direct bluetooth connect solution from mholow with integrated putting from alleexx. 

Everything pretty much works flawlessly. I have no issues with connectivity, putt tracking, etc. GSPro tracks every shot and putt just fine. I can play through flawlessly.

My issue is with the OpenAPI club data viewer. When playing a match, i like to have the OpenAPI app window open on an additional monitor so i can see my swing analytics after each shot. I've noticed that the viewer attempts to "guess" which club I'm using and visually showing either a wood, iron or putter in the window. It's usually pretty accurate. However, after putting out a hole, the data viewer seems to "hang" on the following tee shot for the next hole. GSPro itself is fine..the shot is reflected in my match and all is well. It's just that the data viewer itself doesn't update until the ensuing shot.

**Comment by alleexx** [comment]
I think you need to ask the to gspro guys - either in the discord or in mail. This is just the putting app github.
