### ISSUE TITLE
Ball position at set up not limited to yellow box?

### ISSUE THREAD

**Issue by JustMike70** [alleexx/cam-putting-py#3]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/114702173/226647810-cc9c5db3-2aab-41f2-90d6-f31411fde0ad.png">

As per the picture, the bottom right "diamond" on my mat is being picked up as a potential ball position.  Is there a way to limit where it's looking for the "New ball position" to being within the yellow box where you'd place the ball rather than scanning the whole frame?

**Comment by alleexx** [comment]
The whole width area is being scanned as the ball needs to come out the other side being tracked. You can just limit the height further by adjusting the advanced settings for this not to be a problem. Probably would be even better to get the camera a bit closer to the mat to only have the green of the mat in the view.
