### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by mogema** [alleexx/cam-putting-py#7]
MS Defender Report Trojan:Script/Phonzy.A!ml
[Detected by Microsoft Defender Antivirus](https://www.microsoft.com/en-us/windows/windows-defender?ocid=cx-wdsi-ency)

**Comment by alleexx** [comment]
I found some information on false positives related to pyinstaller which is the python package to make the executable out of the python project files but could not replicate any finding on my machine using latest definiton of MS Defender. Can you check if you have latest virus definiton and let me know the full check results please.

**Comment by alleexx** [comment]
Closing this as I can not replicate with current virus definition files.
