### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by jjaust** [alleexx/cam-putting-py#9]
hello , i cannot for the life of me get this to connect to gsp pro.
Bluetooth connection with r10 works and can hit shots on gs pro
I have installed putting into the same folder at the bluetooth r10connector.
when time to putt the program opens correctly and will read putt data correctly with spped and angle of putt but it seems this data is not accepted by gs pro API. 

the following opens in the debug section of gs pro api

{"DeviceID":"GSPRO-R10","Units":"Yards","ShotNumber":4,"APIVersion":"1","BallData":{"Speed":2.009999990463257,"SpinAxis":0,"TotalSpin":0,"BackSpin":0,"SideSpin":0,"HLA":1.7400000095367432,"VLA":0,"CarryDistance":0},"ShotDataOptions":{"ContainsBallData":true,"ContainsClubData":false}}

i can do multiple putts and newer debug message pops up

i have turned off my firewall, open port 8888 and no difference.

I have tried the other combined adaptor and when choosing the "testshot" tab gs pro will accept it and the golf ball will fly off, but as soon as i try to putt using this interface it hits a deadend as well.

this is what i get on the gs-r10 connect window (after another different put)

20:08:35.454   Putt || Waiting for main window to launch...
20:08:36.463   Putt || Main Window launched
20:08:01.955   Putt >> {"ballData": {"BallSpeed": "2.37", "TotalSpin": 0, "LaunchDirection": "1.01"}}
20:08:01.955  GSPro << {"DeviceID":"GSPRO-R10","Units":"Yards","ShotNumber":5,"APIVersion":"1","BallData":{"Speed":2.369999885559082,"SpinAxis":0,"TotalSpin":0,"BackSpin":0,"SideSpin":0,"HLA":1.0099999904632568,"VLA":0,"CarryDistance":0},"ShotDataOptions":{"ContainsBallData":true,"ContainsClubData":false}}
20:08:02.137  GSPro >> {"Code":200,"Message":"Ball Data received","Player":null}

any ideas??

**Comment by alleexx** [comment]
Hi. I think we had a conversation on this on discord. I hope it is fixed for you. I will close it here. If it is still a problem shoot me a message on discord please.
